version: '3'

services:
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
